### ISSUE TITLE
Can I set a className on the rendered Portal element in order to style it with CSS?

### ISSUE THREAD

**Issue by Zenwolf** [tajo/react-portal#1]
I would like to style the root div element using a CSS class. Is there a way to set a className on the Portal, and not just its child content?

**Comment by tajo** [comment]
Why do you need that? Why is not good enough to style just its child content? (You are asking about the empty `div` that is dynamically appended to the document.body, right?)

**Comment by Zenwolf** [comment]
One example is if a web application has some general styles that apply to all HTML elements, such as `position: relative` which is generally desired except in special circumstances. One special circumstance is a modal dialog. The child Portal content cannot escape from its positioned parent, which may inherit positioning from generic CSS. In this case, being able to apply a style makes it much easier to make the modal behavior of absolutely positioning the portal content across the entire screen. Does that make sense?

**Comment by tajo** [comment]
Oh, that's a very valid point. 

Is it good enough to add a CSS class (e.g `react-portal`) to portal root element? I believe React inline styles (and passing them as an another prop) can't be used since the portal root div is created out of React's scope. It would be nice to achieve that though (any idea how?). Will you send a PR?

**Comment by tajo** [comment]
> Is there a way to set a className on the Portal

Or this. It's more explicit for users, therefore better.
