### ISSUE TITLE
Add support / better error logging for functional stateless children components

### ISSUE THREAD

**Issue by Zhang** [tajo/react-portal#117]
Portal will render child stateless children components
`const PopoverMenu = ({...props}) => {`
, but will trigger this error:
<img width="723" alt="screen shot 2016-12-20 at 4 26 28 pm" src="https://cloud.githubusercontent.com/assets/5522395/21371904/231359ea-c6d1-11e6-936b-3592a9e1cbbe.png">

The fix is to write your components like:
`const PopoverMenu = ({...props}) => {`

Unfortunately, this is very unintuitive to debug. It would be helpful to have better error messaging or general support around this issue

**Comment by tajo** [comment]
Your sample code for problem and solution is identical?

**Comment by tajo** [comment]
And yes, the support for functional components is iffy currently.

**Comment by Zhang** [comment]
Oops - wrong paste, I had meant to write: 

`export class PopoverList extends Component {`

**Comment by tajo** [comment]
Hey, please check the new major version of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is the first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks. 

I am happy to discuss this with v4 in mind. If this is still a problem, please re-open/update the issue. Thanks.
