### ISSUE TITLE
`handleOutsideMouseClick` is invoked twice when testing mobile interfaces in Chrome

### ISSUE THREAD

**Issue by matthewgertner** [tajo/react-portal#134]
I'm testing my Cordova app in Chrome. I guess when you set dev tools to simulate taps, both `mouseup` and `touchstart` are triggered when you click outside the portal. As a result, `handleOutsideMouseClick` is invoked twice. Maybe it would make sense to remove the event listeners in `handkeOutsideMouseClick` so it can only ever be invoked once?

**Comment by tajo** [comment]
Hey, please check the new major version of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is the first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks. 

I am happy to discuss this with v4 in mind. If this is still a problem, please re-open/update the issue. Thanks.
