### ISSUE TITLE
Closing portal throws error

### ISSUE THREAD

**Issue by evandavis** [tajo/react-portal#136]
I keep getting `Invariant Error: React DOM tree root should always have a node reference.` when closing my portal, but I'm unable to reproduce it using the examples. :(

Any idea what might throw that error?

**Comment by Ganasist** [comment]
I got this exact error too, hard to describe how I fixed it but I'll try. I'm using an internal background click dismiss as follows:

```
<div>
  <div
    className={styles.dialogBackgroundOverlay}
    onClick={() => closePortal()}
  />
  ...rest of modal here
</div>
```

The above works and does not give an error. But when I did it before like this, there was your error:

```
<div className={styles.dialogBackgroundOverlay} onClick={() => closePortal()}>
   ...rest of modal here
</div>
```

Hope that helps!

**Comment by goldhand** [comment]
I believe this is caused by a race between unmounting the component and the event propagating.
Within your close event handle, add `e.stopPropagation()` and this error should go away.

**Comment by tajo** [comment]
Hey, please check the new major version of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is the first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks. 

I am happy to discuss this with v4 in mind. If this is still a problem, please re-open/update the issue. Thanks.
