### ISSUE TITLE
Thoughts on passing event object from handleWrapperClick to openPortal?

### ISSUE THREAD

**Issue by noah-potter** [tajo/react-portal#139]
Is there a particular reason `handleWrapperClick` doesn't pass the event object when it calls `openPortal`? I'm trying to use the mouse position in `props.onOpen`

I'll submit a PR if this is wanted.

**Comment by tajo** [comment]
Let's revisit this later. I'm doing a big rewrite with v4.

**Comment by tajo** [comment]
Hey, please check the new major version of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is the first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks. 

I am happy to discuss this with v4 in mind. If this is still a problem, please re-open/update the issue. Thanks.
