### ISSUE TITLE
Portal contents re-mount when unmount triggers an update

### ISSUE THREAD

**Issue by smably** [tajo/react-portal#145]
If the portal contents trigger an update on `componentWillUnmount`, the contents of the portal will re-mount after unmount. See test case: https://gist.github.com/smably/7550b9451682ff533b749f24aa57ca23

In the console:
<img width="355" alt="screen shot 2017-04-12 at 2 36 44 pm" src="https://cloud.githubusercontent.com/assets/1466970/24973637/834eb092-1f8d-11e7-996c-c7761cd21a49.png">

I would expect that after the portal closes, it remains closed until re-opened by normal means.

**Comment by dwick** [comment]
i think this is the same issue fixed in https://github.com/tajo/react-portal/pull/124

**Comment by tajo** [comment]
Hey, please check the new major version of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is the first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks. 

I am happy to discuss this with v4 in mind.
