### ISSUE TITLE
using `mouseup` for closeOnOutsideClick behaviour is troublesome

### ISSUE THREAD

**Issue by mateomurphy** [tajo/react-portal#149]
Using `mouseup` means that clicking inside the modal, dragging out, and releasing closes the modal. This is a pretty common occurrence using modals for forms. 

I understand that `mouseup` was used to solve #65 , was using `click` not an option?

**Comment by mukimov** [comment]
Any updates on this?

**Comment by mateomurphy** [comment]
Hi, I'm sorry I didn't get a notification for your commit, I will test it out this week!

**Comment by tajo** [comment]
Hey, please check the new major version of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is the first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks. 

I am happy to discuss this with v4 in mind.
