### ISSUE TITLE
DOMNode is empty...

### ISSUE THREAD

**Issue by onzag** [tajo/react-portal#159]
I have the following code in order to make some animation calculations

```
onOpen(DOMNode){
   
}
```

However I cannot access anything in the DOMNode because the element is just a `<div></div>` without any content at all, there should be another div inside, this makes animating inside pointless because I can't even take measurements.

**Comment by tajo** [comment]
Hey, please check the new major version of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is a first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks.
