### ISSUE TITLE
Style prop on the Portal element does not get updated

### ISSUE THREAD

**Issue by hughlomas** [tajo/react-portal#16]
It seems like the style property on the Portal element is only set on the first render. Changes to the style prop are ignored in subsequent renders. I think this might be related to renderPortal() which seems to create the node and apply the style prop. 

I came across this while trying to reposition the portals after a window resize, the style={{left:x, top:y}} just doesn't have any effect.

**Comment by tajo** [comment]
Yeah, there is a workaround: https://github.com/tajo/react-portal/blob/master/examples/absoluteposition.js (pass the changes through other props and apply them to the root <div> inside of Portal. You can't really update Portal itself since it's not under React's control (React is just rendering into it).
