### ISSUE TITLE
Older React version support

### ISSUE THREAD

**Issue by majapw** [tajo/react-portal#180]
Hi there!

As I highlighted in https://github.com/airbnb/react-dates/pull/819#issuecomment-347374143, for packages that continue to support older versions of React, it's going to be impossible to ever upgrade to v4 of `react-portal` if used in deps. I was wondering if there were any thoughts for releasing a version of this package that would have reasonable fallbacks for react@0.14 and react@15.

Understandable if not, but thought it would be good to get a discussion going. Thanks so much!

FYI @ljharb

**Comment by ljharb** [comment]
It'd be amazing if native portal support, only in React 16, was added either in a v3 minor, or v3-style-fallbacks were added in a v4 minor.

**Comment by ranneyd** [comment]
Keep in mind that react 16's native portal support fundamentally changes
the way this repo works. I think maintaining two versions of the repo that
are implemented fundamentally differently is impractical.

That being said, if you want to fork v3 and make a repo that's like
`react-portal-legacy` and reimplement the new functionality using the old
portal method, you'd probably get a lot of github stars. :)

**Comment by ljharb** [comment]
If it's that fundamentally different, shouldn't it be a different package and a different name?

**Comment by ranneyd** [comment]
Well it's the same API, just different under the hood

**Comment by ranneyd** [comment]
React 16 is fundamentally different under the hood and isn't a new repo...

**Comment by ljharb** [comment]
:-) ok, that's fair - but react is an overarching framework that doesn't depend on another one; react-portal depends on react, and it's generally a best practice to try to support multiple React versions :-/

**Comment by majapw** [comment]
I feel like the difference is that `react-portal` is usually a regular dependency (because it is a component) while `react` as an overarching framework is usually a peer dep.

**Comment by ranneyd** [comment]
Yeah I understand your point. Tbh I've heard much worse
arguments/suggestions. Let me make constructive comments instead :P

Let me start off by asking why using the old version is insufficient. Do
you specifically desire the new `PortalWithState` component, want to have
the latest in case of bugs etc, or just want to have both just in case? All
are valid reasons.

So as I understand/remember it, with v4 the portal was vastly simplified
because of React 16 and called `Portal` and a new (and awesome) component
called `PortalWithState` was added, which leverages `Portal`. Theoretically
`Portal` should be more or less interchangeable with there new and old
implementations.

So I see two options. The first is forking and replacing the `Portal`
implementation with the old one. This is probably relatively easy since all
the code is there. This is a pain, however, because we'd probably have to
manually apply any changes from this repo to that one, unless we did some
really fancy git linking stuff.

The second option is more disruptive, but far better in my opinion. We turn
this repo into a monorepo that houses a legacy and current version. It also
holds an encapsulated, slightly refactored HOC `PortalWithState` that takes
a base `Portal` implementation as a prop and returns a `PortalWithState`
with a custom interior. Each of the public repos implements its own portal,
plugs it into the `PortalWithState`, and exports that and its portal
implementation. We'd have to modify the npm module config and all that, but
this would be much easier to maintain, and allows us to 1) not copy work
and 2) update the legacy version if there are bugs. Since it's a dramatic
change I'd want @tajo to sign off, but I'd definitely help. I'll also
gladly contribute to option 1 if y'all prefer.

Thoughts?

**Comment by tajo** [comment]
@majapw Thanks for raising this issue! When I released V4 I was even about to open a PR for `react-dates` myself until I realized that you won't probably drop support for older versions of React just because of this library. So I didn't do it.

Anyway, I think the right thing to do is implementing a fallback for V4's `<Portal />` component. `<PortalWithState />` should just work without further changes. I really don't want to touch V3.

However, I am worried that react-portal will behave differently when using the native portal API vs older workaround. I feel it's going to happen only in some edge-cases (timing issues, animations...).

Is it fair to introduce a fallback in `v4.1.0` with a disclaimer stating that it's recommended to upgrade to React16 due to possible issues?

**Comment by tajo** [comment]
@ranneyd Help is definitely appreciated! I don't think there is any reason to let consumer chose which inner implementation should be used. We can simply check if `('react-dom').createPortal` exists in run-time and do the fallback if not.

**Comment by ranneyd** [comment]
That's very smart! All the benefits without needing two repos

**Comment by ljharb** [comment]
@tajo's suggestions sound amazing and super on point; that would address the issue spectacularly well, especially if this semver-minor also made sure to expand the peer dep, and *even better*, ran automated tests on all supported React versions.

I [notice](https://github.com/tajo/react-portal/blob/master/.travis.yml) that you're not testing on multiple React versions now; you may be interested in https://github.com/airbnb/react-dates/pull/846 / https://github.com/airbnb/react-with-direction/pull/3, which demonstrates how to trivially test your project against multiple React versions in travis-ci? :-D

**Comment by tajo** [comment]
@ljharb That looks cool. You even merged portal support for enzyme. That makes me happy. Thanks. :)

**Comment by majapw** [comment]
> Is it fair to introduce a fallback in v4.1.0 with a disclaimer stating that it's recommended to upgrade to React16 due to possible issues?

Seems very reasonable. I think a fallback for `Portal` without react@16 seems great.

**Comment by lencioni** [comment]
For packages like react-dates, where we want to be able to support older versions of React and newer versions of React simultaneously, I was hoping that we could simply add `|| ^4.0.0` to the dependency version. https://github.com/airbnb/react-dates/pull/863

Unfortunately, it seems that the API has changed so that instead of using a default import with v3, we need to use a named import with v4.

> Before we were able to do `import Portal from 'react-portal';` It look like with the addition of `PortalWithState`, you now have to `import { Portal } from 'react-portal';`

https://github.com/airbnb/react-dates/issues/860#issuecomment-347678411

What do you think about publishing a semver minor on top of v3 that adds a named export to allow these to be used identically?

**Comment by tajo** [comment]
@lencioni That's a good note but just adding named export would not be enough. V4 is also dropping this weird `isOpened` prop. Actually, the whole V4 is completely different from V3. Fallback seems as the best solution.

**Comment by tajo** [comment]
`v4.1.0` adds fallback for older Reacts.
