### ISSUE TITLE
Close button doesn't set active state properly and will not allow you to reopen the portal

### ISSUE THREAD

**Issue by dderose** [tajo/react-portal#70]
Steps to reproduce issue:

1. Go to the demo: https://miksu.cz/react-portal/
2. Open the first portal
3. Click on the "close this" button in the portal
4. Try and open the first portal again

Now, for more fun, next open the second portal. It will open both portals. 

If you press the esc key at any time after step 4 above it will close the first portal and "fix" the issue. You can visually see this by opening the second portal and pressing the esc key.

I haven't dug into this much but it looks like the active state is not getting set to false when you use the close button.

**Comment by Sediug** [comment]
The problem happens because this.props.closePortal is sending the event to the father so you'll get this.closePortal(event) but the method is closePortal(isMounted). ¿What that means? That means that when you use this.props.closePortal the Portal's function the isMounted will have something so that's not taking the default value (false). Then there is a if conditional like `if (!isMounted) this.setState(active: false)`. Then as you can see that's will be true (the condition) and will skip to set the active to false. Tha's the reason why that happen. I gonna change this an make a pull request.

**Comment by tajo** [comment]
fix released as `v2.1.3`
