### ISSUE TITLE
Render in place?

### ISSUE THREAD

**Issue by FezVrasta** [tajo/react-portal#76]
Is there a way to tell Portal to do nothing and just render the component in place? (keeping the closeOnEsc, closeOnOutsideClick etc?)

It would be useful when I need to render a tooltip in the same context of its parent (I don't always want to move it to the body)

**Comment by tajo** [comment]
No. You can just do something like

```
inPlace ? <MyComponent /> : <Portal><MyComponent /></Portal>
```

**Comment by FezVrasta** [comment]
But then I can't use the close on outside click etc

**Comment by PeteJodo** [comment]
I think this is out of scope for this package. The purpose of this package is to render a component disconnected from the current position in the DOM (hence the name **portal**). You seem to just want the event handlers portion of the code.

It could, however, take a `container` or `target` prop and render the component to that prop but it would still be using `renderSubtreeIntoContainer`. This wouldn't help you though cause it sounds like you want to render to the current React subtree and you'd be fighting React just to make it work when all you want is the event handlers. You should just implement the handlers yourself and do as @tajo said.

On a side note, a `container` prop is not really too useful, it would just shift the responsibilities of managing the DOM node that will be used as a container onto the user. Majority of use cases would just be an appended node onto the body anyway and maybe only on pages with a complex mix of React and normal DOM nodes could it be useful for being able to choose the container of the portal'd component.

**Comment by tajo** [comment]
This library provides a certain level of abstraction. It does not let you to set a target but that makes it easier to use in most cases. Since it's the most popular "portal" solution out there I assume that's what most devs need and I don't plan to change the scope of this project (at least not without a "fight" and very strong arguments).  If you need more powerful and similar library, you can try https://github.com/cloudflare/react-gateway. There are many others.

**Comment by FezVrasta** [comment]
I was just asking for a way to disable the "portal" and keep the rest of the features. Without this. I must re-implement everything twice, one for when the portal is active, one, for when it's not active.

**Comment by PeteJodo** [comment]
@tajo I was just positing a target prop and then argued against it for why it actually wouldn't help for his use-case, hope you didn't misunderstand my intentions there.

@FezVrasta I understand your issue. It sounds like you need a custom solution. You could fork this project and add your own solution that works for you. Adding a prop to defer to normal rendering rather than the portal rendering doesn't seem to be the correct way about it though. A better way would be to decouple the event handling code with the portal code and use higher-order components. Not sure how that would actually work in this case though.
