### ISSUE TITLE
Stateless components

### ISSUE THREAD

**Issue by salzhrani** [tajo/react-portal#81]
function call [here](https://github.com/tajo/react-portal/blob/master/lib/portal.js#L160) returns null if the child is a stateless component. preventing close on escape.

**Comment by tajo** [comment]
Any idea how to fix it? We might just advise people to use React portal with class component.

**Comment by salzhrani** [comment]
Not familiar with the API used, but I would try using `this.node` or `this.node.childNodes[0]` as `root`

**Comment by arcanis** [comment]
It seems that the `React.PropTypes.element` proptypes triggers an error when using stateless components. I feel like it should be `React.PropTypes.node` (and then you could check if it should receive extra props by using `React.isValidElement(this.props.children) || typeof this.props.children === "function"`).

**Comment by sinapinto** [comment]
it's because renderSubtreeIntoContainer returns a ref to the component, and as specified in the react docs, stateless functional components can't have refs.  But this should not affect 'close on escape', only 'close on outside click'.

**Comment by sinapinto** [comment]
@tajo one option is to use `this.node` instead of `this.portal` in case of a functional component. This would cause surprising behavior though. I think warning people about using functional components together with `closeOnOutsideClick` is the best option. How would you feel about a custom propType validation for that case?

**Comment by tajo** [comment]
I would be happy too see a PR and tests!

**Comment by tajo** [comment]
Hey, please check the new major version of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is the first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks. 

I am happy to discuss this with v4 in mind. If this is still a problem, please re-open/update the issue. Thanks.
