### ISSUE TITLE
pass dom node to onUpdate

### ISSUE THREAD

**Issue by ianstormtaylor** [tajo/react-portal#89]
Right now the DOM node is passed to `onOpen`, but if you want to access it in `onUpdate` (or `onClose`) you have to have kept a reference to it. This adds extra work that doesn't seem necessary, since it seems trivial to pass it into those handlers and stay consistent.

**Comment by tajo** [comment]
I'm happy to accept a PR with this!

**Comment by tajo** [comment]
Hey, please check the new major version of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is the first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks. 

I am happy to discuss this with v4 in mind. If this is still a problem, please re-open/update the issue. Thanks.
