### ISSUE TITLE
Respect `onClick` prop on `openByClickOn` element.

### ISSUE THREAD

**Issue by Andreyco** [tajo/react-portal#97]
Trigger element passed via `openByClickOn` is cloned and receives Portal's very own `onClick` handler. Is it acceptable to invoke it's original `onClick` handler as well?

Got working fork, will create PR if proposal accepted.

**Comment by tajo** [comment]
This https://github.com/tajo/react-portal/pull/120 ?

**Comment by tajo** [comment]
Hey, please check the new major version of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is the first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks. 

I am happy to discuss this with v4 in mind. If this is still a problem, please re-open/update the issue. Thanks.
