### ISSUE TITLE
Render portal to a specific target

### ISSUE THREAD

**Issue by fabarea** [tajo/react-portal#99]
Would it be feasible to specify a target, like an "id" attribute, so that the portal is rendered into this container instead of the bottom of the body?  The feature was somehow mentioned [here](https://github.com/tajo/react-portal/issues/76#issuecomment-225646105) and I would need that.

Thanks for all your work!

Update: actually my use case is to render / open the portal outside the React Scope. Is it actually possible?  I am in a mixed context of React / traditional app (!= single page app).

```
<body>
  <div id="my-react-app">
    ... my react app comes here...
  </div>
  <footer>
    <div id="my-portal">
      ... desired portal here, given id="my-portal"...
    </div>
  </footer>
</body>
```

Don't know if it is possible / in the scope of `react-portal`.

**Comment by th3fallen** [comment]
👍  this would be awesome if possible

**Comment by jussch** [comment]
I second this as well, my use case is a touch different though.

My HTML looks like this:
```html
<html>
<head></head>
<body>
  <div id="content">...</div>
</body>
```

And my CSS looks somthing like this:
```css
html, body, #content {
  height: 100%;
}

#content {
  overflow: auto;
}
```

This makes it so that `#content` is the div that controls scrolling on the page, and not body. So when portals get appended to the body, they are outside of the user's scroll. This can also push the whole body down which adds an additional scrollbar along side the `#content` div.

Being able to pass `#content` as a render target for react-portal would really help for this case. Even being able to pass an element directly like `<Portal renderTarget={document.getElementById('content')}/>` would be even better. (So the element can be passed down through context or props if necessary.)

**Comment by robinfehr** [comment]
+1

**Comment by tajo** [comment]
https://github.com/tajo/react-portal/pull/100 should be merged soon and released as `v4`
